import Head from 'next/head'
import Footer from './Footer'
import Header from './Header'

const Layout = ({children, page}: any) => {
  
  return (
    <>
      <Head>
        <title>{page}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/StouflyDoc_Logo.svg" />
      </Head>

      <Header />
      <main className={'main mx-auto fadeIn min-h-screen flex-col'}>
        {children}
      </main>
      <Footer />
    </>
  )
}

export default Layout